[package]
name = "kefta_core"
version.workspace = true
edition.workspace = true

authors.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default_error = []

[dependencies]
proc-macro2.workspace = true

