[package]
name = "kefta_core"
version = "0.1.0"
edition = "2021"

[features]
default = ["literal"]
literal = ["litrs"]

[dependencies]
#syn = { version = "1.0.98", features = ["full"] }
#quote = "1.0.20"
proc-macro2 = "1.0.43"
litrs = { version = "0.2.3", optional = true }